### PR TITLE
Add metadata endpoint for healthcheck purposes

### PR DESCRIPTION
**Pull request by Sujimoshi**

### CODE REVIEW

**Comment by Nevon** [comment]
I don't see this endpoint documented anywhere in the Confluent Schema Registry API documentation. Do you have a reference?

**Comment by Sujimoshi** [comment]
Took it from https://github.com/confluentinc/schema-registry#openapi-spec

**Comment by Sujimoshi** [comment]
Such endpoint in Official java client https://github.com/confluentinc/schema-registry/blob/7258349ebe11d5d283faf8e06aff287907ed8b6f/client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java#L970

**Comment by Sujimoshi** [comment]
Also I have this https://gist.github.com/Sujimoshi/79fa52d93df6de2c42d740b222c36cc9
This is TypeScript client generated with [swagger-codegen](https://github.com/swagger-api/swagger-codegen) from OpenAPI spec of schema registry

**Comment by Sujimoshi** [comment]
This one works only with `confluentinc/cp-schema-registry:6.0.0`

**Comment by Nevon** [comment]
I'm not sure that we should introduce this. My reasoning is that, at least the way I see it, this library is not a generic Confluent Schema Registry API client. If it were, it wouldn't have the ability to encode/decode messages - just fetching/registering schemas. Getting cluster metadata and other stuff doesn't seem to belong, and it becomes unclear to me what the scope is.

@erikengervall: You're the main developer of this library, what do you think?

**Comment by erikengervall** [comment]
> I'm not sure that we should introduce this. My reasoning is that, at least the way I see it, this library is not a generic Confluent Schema Registry API client. If it were, it wouldn't have the ability to encode/decode messages - just fetching/registering schemas. Getting cluster metadata and other stuff doesn't seem to belong, and it becomes unclear to me what the scope is.
> 
> @erikengervall: You're the main developer of this library, what do you think?

I agree that it isn't exactly within the scope of this library, I'd recommend setting up health checking independently from this library.

**Comment by Nevon** [comment]
Thanks for your initiative @Sujimoshi, but I'm going to close this PR as a wontfix based on the discussion between myself and Erik. If you want to health check the schema registry, our recommendation is to do that outside of this library.

**Pull request closed without merging**
